### ISSUE TITLE
SignatureDoesNotMatch when getting Subscriptions

### ISSUE THREAD

**Issue by bpm1992** [mj1618/serverless-offline-sns#157]
Hi,
Thanks for the very useful plugin.  It was setting up a new system and cannot seem to get the plugin to work on a newer system with newer packages.  There seems to be some issue with the way it signs the request.  Do you have any suggestions? 

DEBUG[serverless-offline-sns]: starting plugin
DEBUG[serverless-offline-sns]: using specified host 0.0.0.0
DEBUG[serverless-offline-sns]: listening on 0.0.0.0:4002
DEBUG[serverless-offline-sns][server]: configuring route
DEBUG[serverless-offline-sns][adapter]: using endpoint: sns.us-east-1.amazonaws.com
DEBUG[serverless-offline-sns][adapter]: listing subs
DEBUG[serverless-offline-sns][adapter]: {"method":"POST","path":"/","headers":{"User-Agent":"aws-sdk-nodejs/2.1209.0 linux/v14.20.0"},"body":"","endpoint":{"protocol":"https:","host":"sns.us-east-1.amazonaws.com","port":443,"hostname":"sns.us-east-1.amazonaws.com","pathname":"/","path":"/","href":"https://sns.us-east-1.amazonaws.com/"},"region":"us-east-1","_userAgent":"aws-sdk-nodejs/2.1209.0 linux/v14.20.0"}
DEBUG[serverless-offline-sns][adapter]: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
DEBUG[serverless-offline-sns]: subs!: null
Environment: linux, node 14.20.0, framework 3.22.0 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read property 'Subscriptions' of null
    at ServerlessOfflineSns.<anonymous> (/usr/local/src/api/jobprocessor/node_modules/serverless-offline-sns/dist/index.js:347:63)
    at step (/usr/local/src/api/jobprocessor/node_modules/serverless-offline-sns/dist/index.js:33:23)
    at Object.next (/usr/local/src/api/jobprocessor/node_modules/serverless-offline-sns/dist/index.js:14:53)
    at fulfilled (/usr/local/src/api/jobprocessor/node_modules/serverless-offline-sns/dist/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by bpm1992** [comment]
This can be fixed by editing sns-adapter.js and removing the 'endpoint' parameter in the SNS configuration.  This will allow the AWS SDK to pick the correct endpoint.

this.sns = new AWS.SNS({
            //endpoint: this.endpoint,
            region: region,
});

**Comment by bpm1992** [comment]
Created Pull Request with update.

https://github.com/mj1618/serverless-offline-sns/pull/158
