### ISSUE TITLE
Exception after 2 minutes of Lambda execution

### ISSUE THREAD

**Issue by dimitrovs** [mj1618/serverless-offline-sns#30]
Timeout is set to 300 seconds in my serverless.yml. After my Lambda (triggered by SNS offline) executes for 2 minutes I get this exception:

`(node:3811) UnhandledPromiseRejectionWarning: FetchError: request to http://127.0.0.1:4002/stopProjectHandler failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/ec2-user/workspace/api-projects/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:3811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by reje
cting a promise which was not handled with .catch(). (rejection id: 1)`

**Comment by mj1618** [comment]
Just pushed a fix, mind upgrading to v0.40.0 and testing?

**Comment by dimitrovs** [comment]
It doesn't fix it. I think the problem is with the NodeJS server and its timeout default set to 120 seconds: https://stackoverflow.com/questions/26909910/express-4-x-closes-connections-after-2-minutes

**Comment by perkyguy** [comment]
Bringing up a long dead issue, but hopefully the PR I put in should fix this issue. I ran into a similar problem as the @dimitrovs , so it would be great if this got included in some release

**Comment by mj1618** [comment]
Sorry for the delay all, this should be fixed after the merge.
