### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by jackbit** [mj1618/serverless-offline-sns#31]
**Issues**
1. SNS did not run when embeds with SLS OFFLINE
2. SNS can not identify ES6 version like import when run the code;

**Proof of issue**
**1. SNS did not run when embeds with SLS OFFLINE**

```
$ npm run dev:api

> sls offline -P 3030 --noTimeout

Serverless: Bundling with Webpack...
Time: 1621ms
Built at: 4/17/2018 12:26:29 PM
                                             Asset      Size                                           Chunks             Chunk Names
      ... unnecessary info for precompile & below is SNS  ...
[./src/workers/email_error.js] 2.06 KiB {src/workers/email_error} [built]
[./src/workers/import_customer.js] 4.33 KiB {src/workers/import_customer} [built]
    + 32 hidden modules
Serverless: Watching for changes...
Serverless: Starting Offline: dev/eu-west-1.

... unnecessary routes & below is SNS  ...

Serverless: Routes for worker_customer_import:
Serverless: (none)

Serverless: Routes for worker_email_error:
Serverless: (none)

Serverless: Offline listening on http://localhost:3030
```
At this point, we dont see any serverless offline sns, here is the serverless.yml

```
service: group

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-sns

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  state: ${opt:stage, 'dev'}
  config: ${file(config.${self:custom.state}.yml)}
  serverless-offline-sns:
    port: ${self:custom.config.SNS_PORT}
    debug: true
    output: .webpack/service

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 3
  stage: ${self:custom.state}
  region: ${self:custom.config.AWS_REGION_DEFAULT}
  environment:

    ... below is SNS ...

    SNS_ARN: ${self:custom.config.SNS_ARN}
    SNS_ENDPOINT: ${self:custom.config.SNS_ENDPOINT}
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
        - "iot:*"

... below is SNS ...

  worker_group_import:
    handler: src/workers/import_customer.workergroupImport
    events:
      - sns: groupImportCustomer
  
  worker_email_error:
    handler: src/workers/email_error.workerEmailError
    events:
      - sns: workerEmailError
```

**2. SNS can not identify ES5/6/7 version like import when run the code**
```
> sls offline-sns start

Serverless: DEBUG[serverless-offline-sns]: starting plugin
Serverless: DEBUG[serverless-offline-sns]: listening on 127.0.0.1:4002
Serverless: DEBUG[serverless-offline-sns][server]: configuring route
Serverless: DEBUG[serverless-offline-sns][adapter]: using endpoint: http://127.0.0.1:4002
Serverless: DEBUG[serverless-offline-sns][adapter]: listing subs
Serverless: DEBUG[serverless-offline-sns][adapter]: {"method":"POST","path":"/","headers":{"User-Agent":"aws-sdk-nodejs/2.224.1 darwin/v8.9.1"},"body":"","endpoint":{"protocol":"http:","host":"127.0.0.1:4002","port":4002,"hostname":"127.0.0.1","pathname":"/","path":"/","href":"http://127.0.0.1:4002/"},"region":"eu-west-1","_userAgent":"aws-sdk-nodejs/2.224.1 darwin/v8.9.1"}
Serverless: DEBUG[serverless-offline-sns][server]: hello request
Serverless: DEBUG[serverless-offline-sns][server]: {"Action":"ListSubscriptions","Version":"2010-03-31"}
Serverless: DEBUG[serverless-offline-sns][server]: []
Serverless: DEBUG[serverless-offline-sns][server]:
Serverless: DEBUG[serverless-offline-sns][server]: sending: <ListSubscriptionsResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/">
  <ResponseMetadata>
    <RequestId>e0ddc668-5c00-4889-b0ed-1c1e95721786</RequestId>
  </ResponseMetadata>
  <ListSubscriptionsResult>
    <Subscriptions>
    </Subscriptions>
  </ListSubscriptionsResult>
</ListSubscriptionsResponse>
Serverless: DEBUG[serverless-offline-sns][server]:
Serverless: DEBUG[serverless-offline-sns][server]: []
Serverless: DEBUG[serverless-offline-sns][adapter]: {"ResponseMetadata":{"RequestId":"e9818963-7c1b-4431-aaf1-ed9e588abfd0"},"Subscriptions":[]}
Serverless: DEBUG[serverless-offline-sns]: subs!: {"ResponseMetadata":{"RequestId":"e9818963-7c1b-4431-aaf1-ed9e588abfd0"},"Subscriptions":[]}
Serverless: DEBUG[serverless-offline-sns]: subscribing
Serverless: DEBUG[serverless-offline-sns]: subscribe: worker_group_import
Serverless: INFO[serverless-offline-sns]: Creating topic: "groupImportCustomer" for fn "worker_group_import"
Serverless: DEBUG[serverless-offline-sns]: subscribe: worker_email_error
Serverless: INFO[serverless-offline-sns]: Creating topic: "workerEmailError" for fn "worker_email_error"
Serverless: DEBUG[serverless-offline-sns][server]: hello request
Serverless: DEBUG[serverless-offline-sns][server]: {"Action":"CreateTopic","Name":"groupImportCustomer","Version":"2010-03-31"}
Serverless: DEBUG[serverless-offline-sns][server]: []
Serverless: DEBUG[serverless-offline-sns][server]: []
Serverless: DEBUG[serverless-offline-sns][server]: hello request
Serverless: DEBUG[serverless-offline-sns][server]: {"Action":"CreateTopic","Name":"workerEmailError","Version":"2010-03-31"}
Serverless: DEBUG[serverless-offline-sns][server]: []
Serverless: DEBUG[serverless-offline-sns][server]: []
Serverless: DEBUG[serverless-offline-sns][adapter]: arn: {"ResponseMetadata":{"RequestId":"84a7913e-f634-4f69-a335-cb2db67a7d65"},"TopicArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer"}
Serverless: DEBUG[serverless-offline-sns]: topic: {"ResponseMetadata":{"RequestId":"84a7913e-f634-4f69-a335-cb2db67a7d65"},"TopicArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer"}
Serverless: DEBUG[serverless-offline-sns][adapter]: subscribe: group-dev-worker_group_import arn:aws:sns:eu-west-1:123456789012:groupImportCustomer
Serverless: DEBUG[serverless-offline-sns][adapter]: subscribeEndpoint: http://127.0.0.1:4002/group-dev-worker_group_import
Serverless: DEBUG[serverless-offline-sns][adapter]: arn: {"ResponseMetadata":{"RequestId":"80ff9012-5f92-4d63-90ab-dd5b9a456aaa"},"TopicArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError"}
Serverless: DEBUG[serverless-offline-sns]: topic: {"ResponseMetadata":{"RequestId":"80ff9012-5f92-4d63-90ab-dd5b9a456aaa"},"TopicArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError"}
Serverless: DEBUG[serverless-offline-sns][adapter]: subscribe: group-dev-worker_email_error arn:aws:sns:eu-west-1:123456789012:workerEmailError
Serverless: DEBUG[serverless-offline-sns][adapter]: subscribeEndpoint: http://127.0.0.1:4002/group-dev-worker_email_error
Serverless: DEBUG[serverless-offline-sns][server]: hello request
Serverless: DEBUG[serverless-offline-sns][server]: {"Action":"Subscribe","Endpoint":"http://127.0.0.1:4002/group-dev-worker_group_import","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer","Version":"2010-03-31"}
Serverless: DEBUG[serverless-offline-sns][server]: []
Serverless: DEBUG[serverless-offline-sns][server]: [{"SubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer:998928","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer","Endpoint":"http://127.0.0.1:4002/group-dev-worker_group_import","Owner":""}]
Serverless: DEBUG[serverless-offline-sns][server]: hello request
Serverless: DEBUG[serverless-offline-sns][server]: {"Action":"Subscribe","Endpoint":"http://127.0.0.1:4002/group-dev-worker_email_error","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError","Version":"2010-03-31"}
Serverless: DEBUG[serverless-offline-sns][server]: [{"SubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer:998928","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer","Endpoint":"http://127.0.0.1:4002/group-dev-worker_group_import","Owner":""}]
Serverless: DEBUG[serverless-offline-sns][server]: [{"SubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer:998928","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer","Endpoint":"http://127.0.0.1:4002/group-dev-worker_group_import","Owner":""},{"SubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError:705186","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError","Endpoint":"http://127.0.0.1:4002/group-dev-worker_email_error","Owner":""}]
Serverless: DEBUG[serverless-offline-sns][adapter]: successfully subscribed fn "group-dev-worker_group_import" to topic: "arn:aws:sns:eu-west-1:123456789012:groupImportCustomer"
Serverless: DEBUG[serverless-offline-sns][adapter]: successfully subscribed fn "group-dev-worker_email_error" to topic: "arn:aws:sns:eu-west-1:123456789012:workerEmailError"
```
**When standalone offline sns received a message**
```
Serverless: DEBUG[serverless-offline-sns][server]: hello request
Serverless: DEBUG[serverless-offline-sns][server]: {"Action":"Publish","Message":"{\"token\":\"6ea7e72c1e1f1e37c4f94e761e66588da7cab293cecf26347109081b0bdbfc19\",\"apiKey\":\"1636367962656997400.1fbc601e554e8ab576bad5fd7166b60334e57b1ddccfefa8b7cc42f62c943f03\",\"message\":{\"from\":\"error@local.host\",\"to\":\"yacobus@local.host\",\"subject\":\"Serverless Error: asd is not defined\",\"text\":\"Tue, 17 Apr 2018 05:33:44 GMT \\n\\n asd is not defined \\n\\n ReferenceError: asd is not defined\\n    at eval (webpack:///./src/actions/auth/dummy.js?:41:9)\\n    at Generator.next (<anonymous>)\\n    at step (webpack:///./src/actions/auth/dummy.js?:22:191)\\n    at eval (webpack:///./src/actions/auth/dummy.js?:22:437)\\n    at new Promise (<anonymous>)\\n    at eval (webpack:///./src/actions/auth/dummy.js?:22:99)\\n    at AuthDummy.validateInputs (webpack:///./src/actions/auth/dummy.js?:44:7)\\n    at eval (webpack:///./src/actions/base.js?:83:19)\\n    at Generator.next (<anonymous>)\\n    at step (webpack:///./src/actions/base.js?:17:191)\\n    at eval (webpack:///./src/actions/base.js?:17:437)\\n    at new Promise (<anonymous>)\\n    at eval (webpack:///./src/actions/base.js?:17:99)\\n    at Promise (webpack:///./src/actions/base.js?:100:21)\\n    at new Promise (<anonymous>)\\n    at AuthDummy.runTasks (webpack:///./src/actions/base.js?:70:12)\\n    at eval (webpack:///./src/actions/base.js?:120:20)\\n    at Generator.next (<anonymous>)\\n    at step (webpack:///./src/actions/base.js?:17:191)\\n    at eval (webpack:///./src/actions/base.js?:17:361)\\n    at <anonymous>\\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\"}}","TopicArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError","Version":"2010-03-31"}
Serverless: DEBUG[serverless-offline-sns][server]: [{"SubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer:998928","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer","Endpoint":"http://127.0.0.1:4002/group-dev-worker_group_import","Owner":""},{"SubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError:705186","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError","Endpoint":"http://127.0.0.1:4002/group-dev-worker_email_error","Owner":""}]
Serverless: DEBUG[serverless-offline-sns][server]: fetching: http://127.0.0.1:4002/group-dev-worker_email_error
Serverless: DEBUG[serverless-offline-sns][server]: event: {"Records":[{"EventVersion":"1.0","EventSubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError:705186","EventSource":"aws:sns","Sns":{"SignatureVersion":"1","Timestamp":"2018-04-17T05:33:44.623Z","Signature":"EXAMPLE","SigningCertUrl":"EXAMPLE","MessageId":"39078532-e0b8-4412-a758-1fb97223b6fe","Message":"{\"token\":\"6ea7e72c1e1f1e37c4f94e761e66588da7cab293cecf26347109081b0bdbfc19\",\"apiKey\":\"1636367962656997400.1fbc601e554e8ab576bad5fd7166b60334e57b1ddccfefa8b7cc42f62c943f03\",\"message\":{\"from\":\"error@local.host\",\"to\":\"yacobus@local.host\",\"subject\":\"Serverless Error: asd is not defined\",\"text\":\"Tue, 17 Apr 2018 05:33:44 GMT \\n\\n asd is not defined \\n\\n ReferenceError: asd is not defined\\n    at eval (webpack:///./src/actions/auth/dummy.js?:41:9)\\n    at Generator.next (<anonymous>)\\n    at step (webpack:///./src/actions/auth/dummy.js?:22:191)\\n    at eval (webpack:///./src/actions/auth/dummy.js?:22:437)\\n    at new Promise (<anonymous>)\\n    at eval (webpack:///./src/actions/auth/dummy.js?:22:99)\\n    at AuthDummy.validateInputs (webpack:///./src/actions/auth/dummy.js?:44:7)\\n    at eval (webpack:///./src/actions/base.js?:83:19)\\n    at Generator.next (<anonymous>)\\n    at step (webpack:///./src/actions/base.js?:17:191)\\n    at eval (webpack:///./src/actions/base.js?:17:437)\\n    at new Promise (<anonymous>)\\n    at eval (webpack:///./src/actions/base.js?:17:99)\\n    at Promise (webpack:///./src/actions/base.js?:100:21)\\n    at new Promise (<anonymous>)\\n    at AuthDummy.runTasks (webpack:///./src/actions/base.js?:70:12)\\n    at eval (webpack:///./src/actions/base.js?:120:20)\\n    at Generator.next (<anonymous>)\\n    at step (webpack:///./src/actions/base.js?:17:191)\\n    at eval (webpack:///./src/actions/base.js?:17:361)\\n    at <anonymous>\\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\"}}","MessageAttributes":{},"Type":"Notification","UnsubscribeUrl":"EXAMPLE","TopicArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError"}}]}
Serverless: DEBUG[serverless-offline-sns][server]: [{"SubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer:998928","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:groupImportCustomer","Endpoint":"http://127.0.0.1:4002/group-dev-worker_group_import","Owner":""},{"SubscriptionArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError:705186","Protocol":"http","TopicArn":"arn:aws:sns:eu-west-1:123456789012:workerEmailError","Endpoint":"http://127.0.0.1:4002/group-dev-worker_email_error","Owner":""}]
Serverless: DEBUG[serverless-offline-sns][adapter]: calling fn: group-dev-worker_email_error 1
Serverless: DEBUG[serverless-offline-sns]: /projects/cryptoxyz/microservices/group
Serverless: DEBUG[serverless-offline-sns]: require(/projects/cryptoxyz/microservices/group/src/workers/email_error)[workerEmailError]
Serverless: DEBUG[serverless-offline-sns][server]: [object Object]
/projects/cryptoxyz/microservices/group/src/workers/email_error.js:17
import WorkerBase from "workers/base";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at ServerlessOfflineSns.createHandler (/projects/cryptoxyz/microservices/group/node_modules/serverless-offline-sns/dist/index.js:222:23)
    at /projects/cryptoxyz/microservices/group/node_modules/serverless-offline-sns/dist/index.js:201:103
    at /projects/cryptoxyz/microservices/group/node_modules/serverless-offline-sns/dist/sns-adapter.js:152:29
    at Layer.handle [as handle_request] (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/layer.js:95:5)
    at next (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/layer.js:95:5)
    at /projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:335:12)
    at next (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:275:10)
    at /projects/cryptoxyz/microservices/group/node_modules/serverless-offline-sns/dist/sns-server.js:25:13
    at Layer.handle [as handle_request] (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:317:13)
    at /projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:335:12)
    at next (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/projects/cryptoxyz/microservices/group/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:317:13)
    at /projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:335:12)
    at next (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/projects/cryptoxyz/microservices/group/node_modules/body-parser/lib/types/json.js:100:7)
    at Layer.handle [as handle_request] (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:317:13)
    at /projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:335:12)
    at next (/projects/cryptoxyz/microservices/group/node_modules/express/lib/router/index.js:275:10)
    at /projects/cryptoxyz/microservices/group/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/projects/cryptoxyz/microservices/group/node_modules/raw-body/index.js:224:16)
    at done (/projects/cryptoxyz/microservices/group/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/projects/cryptoxyz/microservices/group/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by jackbit** [comment]
snipped code:

```
"use strict";

import WorkerBase from "workers/base";
.... some things ...
import nodemailer     from "nodemailer";
import AWS            from "aws-sdk";

class EmailError extends WorkerBase {
  static main (event) {
    console.log(event);
    console.log(".... this is never called ....");
    const instance = new EmailError(event);
    instance.perform();
  }

  async perform() {
    console.log(this.params)
    if(!this.authorize() || !this.params.message) { return }
    this.sendMail();
  }
  ... some things ...
}

module.exports.workerEmailError = EmailError.main
```

**Comment by jackbit** [comment]
**webpack**

```
const path = require('path');
// eslint-disable-next-line import/no-extraneous-dependencies
const nodeExternals = require('webpack-node-externals');
// eslint-disable-next-line import/no-extraneous-dependencies
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  externals: [nodeExternals()],
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  optimization: {
    // We do not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [['env', { targets: { node: '6.10' } }]],
            },
          },
        ],
      },
    ],
  },

  // Resolve extensions and modules paths
  resolve: {
    extensions: ['.js'],
    modules: [path.join(__dirname, 'src'), './node_modules']
  },

  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
};
```

**Comment by jackbit** [comment]
**package.json**  

```
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-3": "^6.24.1",
    "bable-loader": "0.0.1-security",
    "fake-smtp-server": "^0.7.6",
    "serverless-offline": "^3.20.1",
    "serverless-offline-sns": "^0.40.0",
    "serverless-webpack": "^5.1.1",
    "webpack": "^4.5.0",
    "webpack-node-externals": "^1.7.2"
  }
```

**Comment by jackbit** [comment]
I have tried the following combination but still not work:

**comb1:**
```
plugins:
  - serverless-offline-sns
  - serverless-offline
  - serverless-webpack
```

**comb2:**
```
plugins:
  - serverless-webpack
  - serverless-offline-sns
  - serverless-offline
```

**Comment by ricxsar** [comment]
I also experienced this issue. I hope this will be addressed as soon as possible.

**Comment by mj1618** [comment]
I've got some examples I did a while ago on webpack and typescript, are you able to get these working?
https://github.com/mj1618/serverless-offline-sns-example/tree/webpack-plugin
https://github.com/mj1618/serverless-offline-sns-example/tree/typescript-plugin

**Comment by fx** [comment]
@mj1618 neither of your examples actually _use_ the transpilation, the handler is pure es5, and as such obviously both of them work.

[Easy to explode](https://github.com/mj1618/serverless-offline-sns-example/compare/master...fx:master), though.

Just got back into a 6+month old project that used offline-sns and used to work fine, doesn't anymore. Smells like a regression. It does run webpack first, but it will require/execute the handler from source, not from the transpiled result.

**Comment by mj1618** [comment]
Oh right, ok I’ll take a look at the PR and see what I can do

**Comment by akawalsky** [comment]
Hey all, I made this work by changing the start up hook to occur after `offline:start:init` rather than before. The issue was that the location wasn't being resolved correctly because at the time the `init` function is called, the `this.serverless.service.custom["serverless-offline"]` has not yet been loaded.

```diff
this.hooks = {
-            "before:offline:start": () => this.start(),
-            "before:offline:start:init": () => this.start(),
+            "offline:start:init": () => this.start(),
             "after:offline:start:end": () => this.stop(),
             "offline-sns:start:init": () => {
                 this.start();
```

Once I changed this locally, everything worked! @mj1618 fyi

The downside is that it appears that the function gets loaded on init still, so if you are using webpack watch, the code called by the packaged will not be updated automatically. It seems like a more complete refactor would be required to support that functionality.

**Comment by AmarjitMindtree** [comment]
@jackbit 
You are not starting serverless offline.

try to run command
**sls offline start -P 3030 --noTimeout**

I am sure it will work.

**Comment by mj1618** [comment]
Sorry I can't seem to replicate the issue here - https://github.com/mj1618/serverless-offline-sns-example/tree/webpack-plugin

**Comment by mj1618** [comment]
Maybe a more recent commit has fixed this I'm not sure. Not an issue anymore by the looks of it though.
